FROM adxs/openjdk

COPY sshd /etc/s6-overlay/s6-rc.d/sshd

# 更新包列表和安装所需的软件包, 以及删除缓存
RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    apt-get update && \
    apt-get install -y openssh-server sshpass && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 配置 SSH 服务
RUN mkdir /var/run/sshd && \
    echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config && \
    echo 'root:1111' | chpasswd && \
    ssh-keygen -q -t rsa -b 4096 -N "" -f /root/.ssh/id_rsa  && \
    touch /etc/s6-overlay/s6-rc.d/user/contents.d/sshd