FROM ubuntu:20.04
COPY ./openjdk-8u44-linux-x64.tar.gz /tmp/
RUN /bin/sh -c set -eux; \
    mkdir -p /opt/java/openjdk; \
    tar -zxf /tmp/openjdk-8u44-linux-x64.tar.gz --strip-components=1 -C /opt/java/openjdk/; \
    rm -rf /tmp/openjdk-8u44-linux-x64.tar.gz
ENV JAVA_HOME=/opt/java/openjdk
ENV PATH=$PATH:$JAVA_HOME/bin